# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tₙ=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal    Pₙ=n(3n−1)/2	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hₙ=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T₂₈₅ = P₁₆₅ = H₁₄₃ = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.


def benchmark(func):
    import time

    def wrapper(*args, **kwargs):
        start = time.time()
        return_value = func(*args, **kwargs)
        end = time.time()
        print("[*] Total time taken: {} sec.".format(end - start))
        return return_value

    return wrapper


def triangle(n):
    return n * (n + 1) / 2


def pentagonal(n):
    return n * (3 * n - 1) / 2


def hexagonal(n):
    return n * (2 * n - 1)


@benchmark
def main():
    T = []
    P = []
    H = []
    limit = 100000

    print("Begin")
    for i in range(1, limit + 1, 1):
        T.append(triangle(i))
        P.append(pentagonal(i))
        H.append(hexagonal(i))

    for i in T:
        if i in P and i in H and i >40755 :
            print(int(i))
            break



if __name__ == "__main__":
    main()
